### PR TITLE
Co-authored-by: Hanneslol <hannes@hanneswallin.com>

### PR DESCRIPTION
**Pull request by Owale128**
Added active class and if functions

Co-authored-by: losalmson <losalmson@users.noreply.github.com>
Co-authored-by: LaNtZ445 <LaNtZ445@users.noreply.github.com>

### CODE REVIEW

**Comment by Hanneslol** [comment]
Wow such amazing code

**Review by Hanneslol — COMMENTED** [review]
Lit

**Review by Hanneslol — APPROVED** [review]
sry i forgot to approve

**Review by losalmson — APPROVED** [review]
WOW best ive ever seen

**Pull request merged**
