### PR TITLE
lo är en ko

### PR DESCRIPTION
**Pull request by Hanneslol**

### CODE REVIEW

**Comment by LaNtZ445** [comment]
no good

**Comment by Owale128** [comment]
Inte OK! Ändra genast!

**Review by losalmson — CHANGES_REQUESTED** [review]
Pls change this, not ok, very personal !!

**Review by LaNtZ445 — APPROVED** [review]
good

**Review by LaNtZ445 — CHANGES_REQUESTED** [review]
no good

**Review by LaNtZ445 — COMMENTED** [review]
good 👍

**Comment by Hanneslol** [comment]
i removed the disrespectful comment

**Pull request merged**
